<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OmniPadServer.Core\OmniPadServer.Core.csproj" />
    <ProjectReference Include="..\OmniPadServer.ViGEm\OmniPadServer.ViGEm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\WebClient\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Link>wwwroot\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

</Project>
