<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OmniPadServer.Core\OmniPadServer.Core.csproj" />
    <ProjectReference Include="..\OmniPadServer.ViGEm\OmniPadServer.ViGEm.csproj" />
    <ProjectReference Include="..\OmniPadServer.App\OmniPadServer.App.csproj" />
  </ItemGroup>

</Project>
